- name: jenkins job configuration
  hosts: localhost
  become: true
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - dispatch
      - frontend
      - payment
      - shipping
      - user
  roles:
    - jenkins-jobs
