- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    user: sairam
    password: S@ir&m1221
    url: http://172.31.38.101:8080
